### ISSUE TITLE
Pressing return keypad on iOS doesn't close the keypad

### ISSUE THREAD

**Issue by Extheoisah** [bitcoinsearch/bitcoinsearch-app#103]
When I press the return button after typing my query, It doesn't close the keypad. See the video below.
*Note: the zoom issue you see in the video has been fixed in this pr #102 *

https://github.com/bitcoinsearch/bitcoinsearch-app/assets/60826700/422ce735-d206-4423-aa61-cf66d6eebd05

**Comment by kouloumos** [comment]
@Emmanuel-Develops what's the status of this issue?

**Comment by Emmanuel-Develops** [comment]
> @Emmanuel-Develops what's the status of this issue?

completed!
