### ISSUE TITLE
Mobile design aspect ratio might be too small

### ISSUE THREAD

**Issue by Extheoisah** [bitcoinsearch/bitcoinsearch-app#106]
I compared our app vs Google search focusing on the layout and text of the result page on mobile. One thing that stood out to me was that Google's result text is much easier to read and the colors are vivid even in dark mode as opposed to ours. 
The buttons showing the authors, dates, and the reference link at the top of the main highlighted link are too small. Please see the screenshots below

Just so you know, this is just my opinion and observation. This is a design choice so best to include the designer in this conversation. 

Screenshot 1: Google
![google-iOS](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/60826700/ac335115-3e0a-474c-b74a-efe25c9769b7)

Screenshot 2: Bitcoinsearch iOS
![bitcoinsearch-iOS](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/60826700/901670cf-7342-4433-ac79-f376feb7c611)

Screenshot 3: Bitcoinsearch Android
![bitcoinsearch-android](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/60826700/1d0b7a0d-8516-4435-b2d3-af745d4f914f)

**Comment by paperpsych** [comment]
Hi @Extheoisah thanks for noticing this. You're right about the typeface size and the date, author tags being too small. I've attached a side-by-side view of your screenshot and the one in figma, there are differences that the devs should be able to fix.

![Frame 427320198](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/80f53b3f-2faa-42f2-83c5-67ac614c029f)
