### ISSUE TITLE
QA feedback from product/design team

### ISSUE THREAD

**Issue by paperpsych** [bitcoinsearch/bitcoinsearch-app#108]

**Comment by paperpsych** [comment]
[Art's feedback](https://www.loom.com/share/6d1299a525bd40b99c632b4b4f6f3801)

**Comment by paperpsych** [comment]
1. The corner radius needs to be fixed. And the search bar should be slightly taller, please increase height maybe just by a few (3-5) pixels.

2. The "CTRL+K or /" should use the "Geist" font we have.

3. The search bar's icon should also be of dark color in dark mode. It's white in the light mode

![Frame 427320199](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/04d6101e-111f-4b10-a071-84f17ab00b22)

**Comment by paperpsych** [comment]
The image to text aspect ratio here is off... please make it similar to the second image's ratio !!

![Frame 427320200](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/917f6e01-68e6-470b-b1bf-c0d48b31c539)

**Comment by paperpsych** [comment]
These icons should use our orange color (#F7931A) instead of the blue.

![Frame 427320202](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/91113ade-a167-4e83-83b6-c8458deb6c7b)

**Comment by paperpsych** [comment]
The icons here have very low visibility, they'll need to be of the same color as the text beside them like in the second image.

![Frame 427320203](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/063f0882-3c80-4f4f-b1e8-20cfad3d7f0b)

**Comment by paperpsych** [comment]
When a person clicks on the the author or source drop down arrow, the other elements get pushed down, as seen in the image below - when the authors drop down is clicked, the sources filter section is pushed down. This is the correct interaction.

![Frame 427320204](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/4a2c4725-faa4-4795-9d3f-8a6c0c8d8d1e)

What needs to change is what happens when the "Sort by" drop down is clicked. The options for the sort by filters tend to overlap the authors filter section.

![Frame 427320205](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/e2817a70-0e1b-4830-bf70-bed86dfabc38)

The interaction should be the same as between authors and sources. When the sort by drop down is clicked, the authors adn sources filter section should be simply pushed down.

![Frame 427320206](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/76a250ff-470b-44d1-8577-5535f0baac78)

**Comment by paperpsych** [comment]
Here the tooltip (All Tools by the Bitcoin Dev Project) appears when a person hovers over the "all apps" button. Works great.

What's also happening is that after the all apps button is clicked if any of the options is being hovered over, the tooltip is appearing again as if it's being triggered by hovering over the options, this shouldn't be happening.

https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/253d2a49-2bfb-4b22-9533-8cb844fd4048

Also, a few more fixes:

1. The color is different. It should be #292929 instead of dark blue
2. The font weight should be "Medium" instead of bold.
3. Please have the text appear in two lines like in the image on the left instead of three lines.
4. The sun, moon, all apps icons could be slightly larger in size and the moon's outline should be dark instead of orange.

![Frame 427320207](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/2410a0aa-56e1-4fb9-8c5a-a097eeb4c7f1)


5. There's this blue diamond appearing in the dark mode tooltip, that needs to be of the same color as the rest of the tooltip's background.

![Frame 4273210207](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/83b69d40-1ba9-451d-919b-99c6ff5a9d84)

6. The background color of the tooltip and the nav bar is blending with each other. Please change the tooltip's background color to #3A3A3C

![Frame 427320208](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/149538435/b8603163-a3ae-4ebe-ad52-b3069f38054f)

**Comment by Extheoisah** [comment]
closing this as the issues has been addressed in the new staging deployment
