### ISSUE TITLE
Add github actions to enforce global code check on pull request (development)

### ISSUE THREAD

**Issue by Extheoisah** [bitcoinsearch/bitcoinsearch-app#56]
There is currently no check for errors in the code for every pull request to main on github. This requires that the reviewer manually check for these errors or check out the PR locally to review.
Hence, this can silently introduce bugs or silent errors in the app.

This can be mitigated by setting up an automated github actions workflow to check the code for errors (linting or spelling errors and later unit or e2e tests) on every pull request to main. If there are any errors, it will be flagged, thereby narrowing the workload of the reviewer as he only has to focus on the code functionality review and other parameters.

**Comment by adamjonas** [comment]
Thanks for the contribution @Extheoisah. We are relying on netlify at the moment for the sanity check. I'm +0 on adding something else at the moment but will defer to @Emmanuel-Develops if he has a strong preference.

**Comment by Emmanuel-Develops** [comment]
> Thanks for the contribution @Extheoisah. We are relying on netlify at the moment for the sanity check. I'm +0 on adding something else at the moment but will defer to @Emmanuel-Develops if he has a strong preference.

Extra check is always welcome. @adamjonas Kindly review the PR

**Comment by nully0x** [comment]
@Emmanuel-Develops saw this in the todo and there has been some conversation regarding it. Are you actively on it?

**Comment by kouloumos** [comment]
@Emmanuel-Develops linter and build checks run through vercel on every PR now, right? Can we close this?
