### ISSUE TITLE
Do not show side bar when there are no search results

### ISSUE THREAD

**Issue by Extheoisah** [bitcoinsearch/bitcoinsearch-app#58]
The app preserves the state of the side bar when there is no search result.

Expected behaviour: When there is no search results, we should see the side bar. Also, if I previously searched for an query with result and I make a new query that doesn't return a result, the state of the side bar should be updated so that we do not see the `author` or `sort by date` side bar of the previous search.

See images below for reference.

<img width="1480" alt="Screenshot 2023-02-18 at 08 09 25" src="https://user-images.githubusercontent.com/60826700/219849813-d4add317-5a67-4b35-970c-89c1c39c4e22.png">
<img width="1673" alt="Screenshot 2023-02-18 at 08 10 29" src="https://user-images.githubusercontent.com/60826700/219849816-f106804d-bb25-45b0-b9e6-0f12c58f09b1.png">

**Comment by Emmanuel-Develops** [comment]
Good find! @Extheoisah  I'll get started on that
