### ISSUE TITLE
GitHub org page displays a broken link

### ISSUE THREAD

**Issue by satsie** [bitcoinsearch/bitcoinsearch-app#66]
The organization page, https://github.com/bitcoinsearch, has a broken link. Currently it is:

http://bitcoinseach.xyz/

![Screenshot from 2023-03-15 15-52-02](https://user-images.githubusercontent.com/1823216/225426826-07b9807d-4c1b-42a0-b455-4d0c41fce65d.png)

But it should be:

https://bitcoinsearch.xyz/

(the r in "search" is missing and probably want to make the link https)

**Comment by adamjonas** [comment]
Blerg. Thanks. It's been updated.
