### ISSUE TITLE
UI Revamp 

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcoinsearch/bitcoinsearch-app#86]
Implementation of the new UI design revamp for bitcoin search 
[Figma link here](https://www.figma.com/file/d43NNG3nVnDQcuvloueVbD/BTC-SEARCH-Product?type=design&node-id=75-9109&mode=design)

also addresses #79

**Comment by Extheoisah** [comment]
duplicate issue #90 . Moved to project board
