### ISSUE TITLE
New UI redesign

### ISSUE THREAD

**Issue by Extheoisah** [bitcoinsearch/bitcoinsearch-app#90]
Implementation of the new UI design revamp for bitcoin search
[Figma link here](https://www.figma.com/file/d43NNG3nVnDQcuvloueVbD/BTC-SEARCH-Product?type=design&node-id=75-9109&mode=design)

also addresses https://github.com/bitcoinsearch/bitcoinsearch-app/issues/79

**Comment by Extheoisah** [comment]
1. Build a new footer component https://github.com/bitcoinsearch/bitcoinsearch-app/pull/88
2. Build a new search component https://github.com/bitcoinsearch/bitcoinsearch-app/pull/87

**Comment by kouloumos** [comment]
@Extheoisah should we close this one?

**Comment by Extheoisah** [comment]
Yeah, we can.
